project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
        text: Timeline
      - href: publications.qmd
        text: Publications
      - href: blog
        text: Blog
      - href: cv/Zeel_CV.pdf
        text: CV
      - href: apps.qmd
        text: Apps

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: styles.scss
    toc: true
